FROM golang:1.19-alpine3.18 AS builder

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

WORKDIR /opt

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev python3

RUN mkdir /opt/coordinator

COPY . /opt/coordinator/

ENV GOPROXY=https://goproxy.cn,direct

RUN cd /opt/coordinator \
    && go install ./cmd/coordinatord

FROM alpine:3.15

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

ENV PATH="/path/to/bash:$PATH"

COPY --from=builder /go/bin/coordinatord /usr/local/bin/

RUN ls -al /opt/coordinator

COPY --from=builder /opt/coordinator/tests/docker/scripts/start_coordinator.sh /opt/start_coordinator.sh
COPY --from=builder /opt/coordinator/tests/docker/scripts/helper.sh /opt/helper.sh

RUN chmod +x /opt/start_coordinator.sh
RUN chmod +x /opt/helper.sh

EXPOSE 26657 26656 1317 9090

ENTRYPOINT ["/opt/start_coordinator.sh"]
