FROM golang:1.19-alpine3.18 AS builder

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

WORKDIR /opt

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev python3

RUN mkdir /opt/consumer

COPY . /opt/consumer/

ENV GOPROXY=https://goproxy.cn,direct

RUN cd /opt/consumer \
    && go install ./cmd/consumerd

FROM alpine:3.15

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk add --update bash jq

ENV PATH="/path/to/bash:$PATH"

COPY --from=builder /go/bin/consumerd /usr/local/bin/

COPY --from=builder /opt/consumer/tests/docker/scripts/scripts/start_consumer.sh /opt/start_consumer.sh
COPY --from=builder /opt/consumer/tests/docker/scripts/scripts/helper.sh /opt/helper.sh

RUN chmod +x /opt/start_consumer.sh
RUN chmod +x /opt/helper.sh

EXPOSE 26657 26656 1317 9090

ENTRYPOINT ["/opt/start_consumer.sh"]
