FROM golang:1.18-alpine3.15 AS builder

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

ENV GOPROXY=https://goproxy.cn,direct

WORKDIR /opt

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev python3

RUN git clone https://github.com/cosmos/relayer.git \
    && cd relayer \
    && git checkout v2.3.0 \ 
    && make install

FROM alpine:3.15

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

ENV GOPROXY=https://goproxy.cn,direct

RUN apk add --update bash jq

ENV PATH="/path/to/bash:$PATH"

COPY ./scripts/config/relayer_config.yaml /root/.relayer/config/config.yaml
COPY ./scripts/start_relayer.sh /opt/start_relayer.sh

COPY --from=builder /go/bin/rly /usr/local/bin/

ENTRYPOINT ["/opt/start_relayer.sh"]
